### PR TITLE
#122 q22 duplicate option

### PR DESCRIPTION
**Pull request by gernotstarke**

### CODE REVIEW

**Comment by gernotstarke** [comment]
maybe we need to increase the rev number... I forgot to check

**Review by programming-wolf — CHANGES_REQUESTED** [review]
Revision number is not supposed to be in that document. It is only appended via the commit tag. `document.version` should only contain 2021.2. Can you please fix this? :)

**Comment by gernotstarke** [comment]
I object. The currently published documents contain the revision number in the footer. We may increase the version id and release 2022.1

Screenshot 2022-12-02 um 12 11 17

**Comment by programming-wolf** [comment]
Ah, right. It's the examination. I'll approve

**Review by programming-wolf — APPROVED** [review]

**Pull request merged**
