### PR TITLE
#126 improve terms to clarify the intent of the question

### PR DESCRIPTION
**Pull request by feststelltaste**
Changed "Führung" / "maintaining" to "Einführung" / "introduction" (and removing "adequate", because IMHO it has nothing to do with the question in this context). I also added a brief explanation on the answers.

### CODE REVIEW

**Comment by gernotstarke** [comment]
@feststelltaste one concern we (the Foundation-Working-Group) has with the mock exam is the risk of overfitting:

In case we fix errors, we make the mock-exam (much) better than we assume the _real_ exam is...
Therefore we left MANY issues open.

Next Monday I will discuss this with @alxlo f2f - until then I will leave your PR open.

**Comment by alxlo** [comment]
My students and I always struggle with this question as well and improving it is not considered overfitting by me. 
However, the pull request improves things a bit but IMHO not enough. It's just too much a case of "it depends" and while for starting to finally have an architecture documentation at all, increasing  testability may not be the main driver, it may be very well a contributing factor. 

So either we should turn this into a P-Question ("select the usually most important ...") or use a distractor that should clearly be not a motivating factor (yes, hard to find, there are a thousand reasons to get documentation started).

**Comment by alxlo** [comment]
also see #100

**Comment by gernotstarke** [comment]
@alxlo could you propose additional improvements, so we can get this PR into production?

**Comment by rhoadesre** [comment]
Suggestions for possible distractors:

1. To ensure that all requirements are documented
2. To ensure that external users (e.g., customers, partners etc.) are aware of how the system is implemented.
3.

**Comment by ulibecker** [comment]
I agree with @alxlo that a P-Question would fit better here

**Pull request merged**
