### PR TITLE
Rephrase one english answer on question 32

### PR DESCRIPTION
**Pull request by mgrig**

### CODE REVIEW

**Comment by gernotstarke** [comment]
if we merge this, we need to adjust the version id for the EN version.

Any objections?

**Comment by programming-wolf** [comment]
It's a bug fix, so I'd only increase the revision.  :-)

**Comment by alxlo** [comment]
> 



> It's a bug fix, so I'd only increase the revision. :-)
Definitely. Changing major/minor was never on the table ;-) 
My point was another, but that is totally beyond scope here. So we keep German at rev8 and increase English to rev9? Right?

Content-wise I'm fine, although the precise wording might start a >30 minute discussion if this would be a real exam question. But it's good enough.

**Comment by programming-wolf** [comment]
Revision is increased for the whole document repository, so German would be the same revision, even though nothing changed. And it is only a mock exam ;)

**Pull request merged**
